triggers:
- description: null
  envs: []
  last_enabled_at: 2024-09-27 21:50:17.116355+00:00
  name: Real -time prediction
  pipeline_uuid: predict
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-09-27 21:07:00+00:00
  status: active
  token: 0584dd355b4046d299869eccc96bd2fe
  variables: {}
