#config file version
apiVersion: 1

#list of datasources to list/update
#available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: test
    user: postgres
    secureJsonData:
      password: pass
    jsonData:
      sslmode: 'disable'
      database: test
  